# recipe from https://github.com/SciTools/conda-recipes-scitools
package:
  name: proj4
  version: !!str 4.9.1
source:
  fn:  proj-4.9.1.tar.gz
  url: http://download.osgeo.org/proj/proj-4.9.1.tar.gz

about:
  home: http://trac.osgeo.org/proj/
  license: MIT
  summary: 'Cartographic projection software'
