package:
    name: g2clib
    version: !!str 1.4.0

source:
    fn: g2clib-1.4.0.tar
    url: http://www.nco.ncep.noaa.gov/pmb/codes/GRIB2/g2clib-1.4.0.tar
    md5: f0cbab4ebbaec6d8dd15da1a36c93675

    patches:
        # patch to set makefile appropiately
        - patch1.patch

build:
    number: 0

requirements:
    build:
        - jasper
        - libpng
        - zlib

    run:
        - jasper
        - libpng
        - zlib

test:
    imports:

about:
    home: http://www.nco.ncep.noaa.gov/pmb/codes/GRIB2/ 
    license: BSD-style (http://www.hdfgroup.org/ftp/HDF/current/src/unpacked/COPYING)
